name: 'Test'
description: 'testing'
inputs:
    GITHUB_TOKEN:
      description: 'Github token of the repository (automatically created by Github)'
      required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
