on: [pull_request]

jobs:
  test_comment:
    runs-on: ubuntu-latest
    name: Comment Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment files length
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}