on:
  pull_request:
    types: [opened]

jobs:
  test_comment:
    runs-on: ubuntu-latest
    name: Comment Files
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Comment files length
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}